spring.datasource.url=jdbc:postgresql://localhost:5432/bankdesk
server.port=8080
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=yusufsami
spring.jpa.show-sql=true